### ISSUE TITLE
migrate jcenter to mavenCentral

### ISSUE THREAD

**Issue by underwindfall** [underwindfall/PowerPermission#29]

**Comment by kalpeshk95** [comment]
PowerPermission not working in new Studio is this because of jcenter deprecation?

**Comment by kalpeshk95** [comment]
ok

**Comment by underwindfall** [comment]
@kalpeshk95 hello sorry for the delay, I finally find some time to deal with this issue. Now, `1.5.0` will be hosted in 
**mavenCentral**.
